"""Markdown report renderer (great for PR comments / CI artifacts)."""

from __future__ import annotations

from ..models import Grade, Report

_ORDER = {Grade.DANGER: 0, Grade.WARN: 1, Grade.UNKNOWN: 2, Grade.OK: 3}


def render_md(report: Report) -> str:
    c = report.counts()
    lines = []
    lines.append("# pkgguard report")
    lines.append("")
    lines.append(
        f"**{c['ok']}** ✅ ok  ·  **{c['warn']}** ⚠️ warn  ·  "
        f"**{c['danger']}** ❌ danger  ·  **{c['unknown']}** ❔ unknown"
    )
    lines.append("")
    lines.append("| Verdict | Item | Ecosystem | Summary |")
    lines.append("|---|---|---|---|")

    for ir in sorted(report.items, key=lambda r: _ORDER[r.grade]):
        name = ir.item.name.replace("|", "\\|")
        summary = (ir.summary or "").replace("|", "\\|")
        lines.append(
            f"| {ir.grade.emoji} {ir.grade.label} | `{name}` | "
            f"{ir.item.ecosystem} | {summary} |"
        )
    lines.append("")

    # Detail for everything that isn't a clean pass.
    flagged = [ir for ir in report.items if ir.grade is not Grade.OK]
    if flagged:
        lines.append("## Details")
        lines.append("")
        for ir in sorted(flagged, key=lambda r: _ORDER[r.grade]):
            lines.append(f"### {ir.grade.emoji} `{ir.item.name}` ({ir.item.ecosystem})")
            for f in ir.findings:
                lines.append(f"- **{f.title}** _({f.severity.value})_")
                if f.detail:
                    lines.append(f"  - {f.detail}")
            meta = ir.meta
            extras = []
            if meta.get("github"):
                gh = meta["github"]
                extras.append(f"{gh.get('stars', 0)}★")
                if meta.get("license"):
                    extras.append(str(meta["license"]))
            if extras:
                lines.append(f"  - _repo: {' · '.join(extras)}_")
            lines.append("")

    lines.append("---")
    lines.append("_Generated by [pkgguard](https://github.com/Highcrypto7/pkgguard) — "
                 "vet what your AI recommended before you install._")
    return "\n".join(lines)
